   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: astronomer-airflow
     labels:
       app: astronomer-airflow
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: astronomer-airflow
     template:
       metadata:
         labels:
           app: astronomer-airflow
       spec:
         containers:
         - name: astronomer-airflow
           image: astronomerinc/ap-airflow:2.2.0  # Substitua pela versão desejada
           ports:
           - containerPort: 8080
           env:
           - name: AIRFLOW__CORE__EXECUTOR
             value: "LocalExecutor"  # Ou "CeleryExecutor" se você estiver usando o Celery
           - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
             value: "postgresql+psycopg2://user:password@postgres:5432/airflow"  # Ajuste conforme necessário
           # Adicione outras variáveis de ambiente conforme necessário