apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "airflow_user"  # Substitua pelo seu usuário
        - name: POSTGRES_PASSWORD
          value: "airflow_password"  # Substitua pela sua senha
        - name: POSTGRES_DB
          value: "airflow_db"  # Substitua pelo seu nome de banco de dados
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres