   apiVersion: v1
   kind: Service
   metadata:
     name: astronomer-airflow
   spec:
     type: NodePort  # Ou NodePort, dependendo da sua configuração
     ports:
     - port: 8080
       targetPort: 8080
     selector:
       app: astronomer-airflow